name: trajectory-env
channels:
 - bioconda
 - conda-forge
 - defaults
dependencies:
 - rstudio=1.1.456
 - bioconductor-destiny=2.15
 - bioconductor-slingshot=1.4
 - bioconductor-tradeseq=1.0
 - bioconductor-singlecellexperiment=1.8
 - libgfortran
 - libopenblas=0.3.7
 - r-bookdown
 - r-hdf5r
 - r-optparse
 - r-seurat=3.0.2
 - r-stringi=1.4.3=r36h29659fb_0
 - r-umap
 - r-uwot
 - wget
 
 