name: velocyto-env
channels:
  - anaconda
  - bioconda
  - defaults
dependencies:
  - click=7.1.1
  - cython=0.29.15
  - h5py=2.10.0
  - matplotlib=3.1.3
  - numba=0.48.0
  - numpy=1.18.1
  - samtools=1.9
  - scikit-learn=0.22.1
  - scipy=1.4.1

