name: Sauron.v1
channels:
 - conda-forge
 - bioconda
 - defaults
 - anaconda
dependencies:
 - r-base=3.5
 - rstudio=1.1.456
 - bioconductor-biomart=2.38
 - bioconductor-flowpeaks=1.28
 - bioconductor-genomeinfodbdata=1.2.0
 - bioconductor-scater=1.10
 - bioconductor-scran=1.10
 - bioconductor-singlecellexperiment=1.4
 - bioconductor-sva=3.30
# - bioconductor-slingshot=1.2.0
# - bioconductor-destiny=2.12.0
 - bioconductor-monocle=2.10.0
 - r-devtools=2.1.0
 - r-biocmanager=1.30
 - r-data.table=1.11
 - r-dbscan=1.1
 - r-dplyr=0.8
 - r-fields=9.6
 - r-igraph=1.2
 - r-ineq=0.2
 - r-optparse=1.6
 - r-pheatmap=1.0
 - r-rafalib=1.0
 - r-rcolorbrewer=1.1
 - r-scales=1.0
 - r-seurat=3.0.1
 - r-vegan=2.5
 - r-venn=1.7
 - r-hdf5r=1.2.0
 - r-umap=0.2
 - leidenalg=0.7.0
 - umap-learn=0.3.7
 - r-grr=0.9.5
 - r-pbmcapply=1.4.1
 - r-plot3d=1.1.1
 - r-circlize
 - r-wgcna
# - snakemake=5.5.4
# - r-raceid=0.1.3
 - wget=1.19.4  # For compatibility with genomeinfodbdata (currently broken)
